---
- name: "PLAY 1: Manage VPNs with cli_config and jinja2"
  hosts: R1
  connection: network_cli
  tasks:
    - name: "TASK 1: Store platform-specific template path"
      set_fact:
        vpn_path: "templates/{{ ansible_network_os }}_del_int.j2"

    # It's gonna run only if the ansible_network_os is equal to junos
    - name: "TASK 2: Apply generic VPN config via SSH/CLI in Junos Plataform"
      junos_command:
        commands: "{{ lookup('template', vpn_path) }}"
      notify: config_changed
      register: cli_result
      when: ansible_network_os == "junos"

    # It's gonna run only if the ansible_network_os is equal to iosxr or ios
    - name: "TASK 3: Apply generic VPN config via SSH/CLI in Cisco Plataform"
      cli_config:
        config: "{{ lookup('template', vpn_path) }}"
      notify: config_changed
      register: cli_result
      when: ansible_network_os == "ios" or ansible_network_os == "iosxr"

  handlers:
    - name: "HANDLER 1: Display relevant changes"
      listen: config_changed
      debug:
        msg: "{{ cli_result }}"
