---
all:
  children:
    routers:
      children:
        ios_routers:
          hosts:
            R1:
              ansible_host: 1.1.1.1
        iosxr_routers:
          hosts:
            R2:
              ansible_host: 1.1.1.2        
        junos_routers:
          hosts:
            R3:
              ansible_host: 1.1.1.3
